// <auto-generated />
using System;
using CSU.EtapaTecnica.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSU.EtapaTecnica.Data.Migrations
{
    [DbContext(typeof(CSUContext))]
    [Migration("20220404141506_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSU.EtapaTecnica.Domain.Models.NotaFiscal", b =>
                {
                    b.Property<int>("CodNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODNOTA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodVenda")
                        .HasColumnName("CODVENDA")
                        .HasColumnType("int");

                    b.Property<string>("DestinatarioRemetente")
                        .HasColumnName("DESTINATARIOREMETENTE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DtEmissao")
                        .HasColumnName("DTEMISSAO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtSaidaEntrada")
                        .HasColumnName("DTSAIDAENTRADA")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumNota")
                        .HasColumnName("NUMNOTA")
                        .HasColumnType("int");

                    b.Property<string>("NumeroRecibo")
                        .HasColumnName("NUMERORECIBO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TransFrete")
                        .HasColumnName("TRANSFRETE")
                        .HasColumnType("int");

                    b.Property<double?>("ValorTotalNota")
                        .HasColumnName("VALORTOTALNOTA")
                        .HasColumnType("float");

                    b.Property<double?>("ValorTotalProdutos")
                        .HasColumnName("VALORTOTALPRODUTOS")
                        .HasColumnType("float");

                    b.HasKey("CodNota")
                        .HasName("PK_NOTA_FISCAL");

                    b.ToTable("NOTA_FISCAL");
                });

            modelBuilder.Entity("CSU.EtapaTecnica.Domain.Models.NotaFiscalItem", b =>
                {
                    b.Property<int>("CodItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODITEM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodNota")
                        .HasColumnName("CODNOTA")
                        .HasColumnType("int");

                    b.Property<int>("CodPro")
                        .HasColumnName("CODPRO")
                        .HasColumnType("int");

                    b.Property<string>("CodigoProdutoExterno")
                        .HasColumnName("CODIGOPRODUTOEXTERNO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DescrPro")
                        .HasColumnName("DESCRPRO")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<double>("Qtde")
                        .HasColumnName("QTDE")
                        .HasColumnType("float");

                    b.Property<string>("Unidade")
                        .HasColumnName("UNIDADE")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<double>("ValorTotal")
                        .HasColumnName("VALORTOTAL")
                        .HasColumnType("float");

                    b.Property<double>("ValorUnitario")
                        .HasColumnName("VALORUNITARIO")
                        .HasColumnType("float");

                    b.HasKey("CodItem")
                        .HasName("PK_NOTAFISCALITENS");

                    b.HasIndex("CodNota")
                        .HasName("IX_NOTAFISCALITENS_CODNOTA");

                    b.ToTable("NOTAFISCALITENS");
                });

            modelBuilder.Entity("CSU.EtapaTecnica.Domain.Models.NotaFiscalItem", b =>
                {
                    b.HasOne("CSU.EtapaTecnica.Domain.Models.NotaFiscal", "NotaFiscal")
                        .WithMany("Produtos")
                        .HasForeignKey("CodNota")
                        .HasConstraintName("FK_NOTAFISCALITENS_NOTAFISCAL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
