CREATE TABLE "NOTA_FISCAL"
(
  "CODNOTA"  INTEGER NOT NULL,
  "CODVENDA"  INTEGER,  
  "DESTINATARIOREMETENTE"  VARCHAR(100),  
  "DTEMISSAO"  DATE,
  "DTSAIDAENTRADA"  DATE,    
  "NUMNOTA"  INTEGER,  
  "VALORTOTALPRODUTOS"  DOUBLE PRECISION,
  "VALORTOTALNOTA"  DOUBLE PRECISION,    
  "TRANSFRETE"  INTEGER,        
  "NUMERORECIBO"  VARCHAR(50),  
 PRIMARY KEY ("CODNOTA")
);
